### ISSUE TITLE
[Feature] Support `arguments` keyword

### ISSUE THREAD

**Issue by fh2ctm** [acristoffers/tree-sitter-matlab#11]
It would be good to add [argument validation](https://www.mathworks.com/help/matlab/ref/arguments.html) syntax. 

Minimal (non-)working example: 

```matlab
function [y] = f(x)
  arguments
    x (1,36) double
  end
end
```

**Comment by acristoffers** [comment]
It's already implemented:

![image](https://github.com/user-attachments/assets/47a5ab83-66d8-4a50-b1f3-be1940022cc0)

If what you are talking about is highlight in your editor, it is editor-dependent and may be affected by plugins.

**Comment by fh2ctm** [comment]
I see. Thank you for the reply!

> If what you are talking about is highlight in your editor, it is editor-dependent and may be affected by plugins.

I'm having issues with [`nvim-treesitter-context`](https://github.com/nvim-treesitter/nvim-treesitter-context) so I will investigate further.
