### ISSUE TITLE
Enums should support char/strings as argument

### ISSUE THREAD

**Issue by mimmanuel** [acristoffers/tree-sitter-matlab#5]
Thanks for making this grammar, it is really great.

I have an issue using enums. It should be possible to pass a string or char when using an enumeration block

The following code works in MATLAB, but is highlighted incorrectly using Neovim
```matlab
classdef AnEnum
    enumeration
        One ('1')
        Two ('2')
        Ten ('10')
    end

    properties
        string
    end

    methods
        function obj = AnEnum(str)
            obj.string = str;
        end
    end
end
```
Example with strings:
<img width="769" alt="Screenshot 2023-08-22 at 14 41 40" src="https://github.com/acristoffers/tree-sitter-matlab/assets/1974538/6cb66c6c-ce3b-4eb1-bc48-d235ac396f33">

Example without strings:
<img width="757" alt="Screenshot 2023-08-22 at 14 44 00" src="https://github.com/acristoffers/tree-sitter-matlab/assets/1974538/e501540a-a423-490f-b559-cd148a45fd9c">

**Comment by acristoffers** [comment]
Made a new commit fixing that. It should appear in `nvim-treesitter` in a few... minutes? Hours? If the  error persists, please reopen the issue.

And thank you for reporting it! ^^
