### ISSUE TITLE
Indentation after line continuation

### ISSUE THREAD

**Issue by gregdvd** [acristoffers/tree-sitter-matlab#7]
Thanks a lot for providing support for matlab!
I just have a minor suggestion, but I have no idea whether it is simple to implement or not - in my opinion, indentation should be added to the line following a "line continuation" (i.e., the ellipsis `...`).

This is what I get in neovim + treesitter
```matlab
plot(this, is, a, long, list, of, meaningless, ...
arguments)

q = struct(...
'a', 20, ...
'b', 12  ... comment about b
);
```
while this is how it looks like when typed in the matlab editor
```matlab
plot(this, is, a, long, list, of, meaningless, ...
    arguments)

q = struct(...
    'a', 20, ...
    'b', 12  ... comment about b
    );
```
Thanks again!

**Comment by acristoffers** [comment]
This project is only a parser and does not provide any means for code formatting. You need a proper formatter for that.

**Comment by gregdvd** [comment]
I'm sorry if I my comment fell outside the scope of the project. I thought it offered some indentation features through the (experimental) nvim-treesitter indentation module and that my suggestion could be achieved by tuning the contents of `queries/neovim/indents.scm`

Thanks anyway.

**Comment by acristoffers** [comment]
That thing is mostly for things like if/else/function/etc. The indentation is done in a way that I don't think it is even possible to do what you want.
