### ISSUE TITLE
Delimiters in matrices are not highlighted as punctuation

### ISSUE THREAD

**Issue by shanewstone** [acristoffers/tree-sitter-matlab#8]
Thank you for your work on this project.

I have recently started using tree-sitter for `matlab` code and I have found that, when using `tree-sitter-matlab`, delimiters inside matrices are not highlighted as punctuation. That is, the `,` and `;` are not highlighted inside matrices like these:

```
x = [1, 2, 3, 4];
```

```
x = [1; 2; 3; 4];
```

I have had a look at the `grammar.js` and I found that the problem is solved if I replace `$._entry_delimiter` with something simple like `choice(',', ';')` in the definition of `row` (see: [1](https://github.com/acristoffers/tree-sitter-matlab/blob/79d8b25f57b48f83ae1333aff6723b83c9532e37/grammar.js#L343) and [2](https://github.com/acristoffers/tree-sitter-matlab/blob/79d8b25f57b48f83ae1333aff6723b83c9532e37/grammar.js#L345)). I have no doubt this simple "fix" produces other unwanted bugs, but perhaps this indicates that the root cause of this issue lies within the logic of `scan_entry_delimiter` in [scanner.c](https://github.com/acristoffers/tree-sitter-matlab/blob/79d8b25f57b48f83ae1333aff6723b83c9532e37/src/scanner.c#L785). I am not certain, so I thought I would file an issue here.

**Comment by acristoffers** [comment]
In tree-sitter, rules starting with a underscore, like `$._entry_delimiter`, do not generate a node. That's why it's not being colored: there is no node for it. I pushed a commit that generates a node for them so they will now get highlighted.
