### ISSUE TITLE
`~` and `"` are not highlighted as operators

### ISSUE THREAD

**Issue by shanewstone** [acristoffers/tree-sitter-matlab#9]
I believe the not operator `~` should be highlighted as an operator as it is in other languages rather than `@constant.builtin`.

Similarly, single quotes `'` are currently highlighted as operators, while double quotes `"` are highlighted as parts of the string they begin/end. I believe double quotes should be highlighted as operators, the same as single quotes.

If I am not mistaken, both of these issues are easily fixed by adding `"~"` and `"\""` to the list of operators in `highlights.scm`, e.g. [for helix](https://github.com/acristoffers/tree-sitter-matlab/blob/79d8b25f57b48f83ae1333aff6723b83c9532e37/queries/helix/highlights.scm#L85).

I can certainly file a pull request for the three `highlights.scm` if this sounds acceptable.

**Comment by acristoffers** [comment]
~ can be seen as an operator, but string delimiters for sure are not. Anyways, the queries in this repo are there mostly for reference, if you want to have those changes in your editor you have to actually go after each downstream project: helix, nvim-tressitter and emacs-tree-sitter-langs. They handle their queries themselves and do not pull them from here.
